### ISSUE TITLE
Hot reloading, Webpack and ESLint ideas etc.

### ISSUE THREAD

**Issue by ghenry** [librestack/libreum#36]
SImilar to https://github.com/vuejs/vue-cli to create (https://vuejs.org/v2/guide/single-file-components.html)

Then you can do things like:

npm run dev
npm build etc.

A joy! Right now I can't test even after copying in js and css:

![screenshot from 2018-01-18 15-18-15](https://user-images.githubusercontent.com/159608/35105224-fbaec1e6-fc62-11e7-8250-649cd6808a1d.png)

**Comment by brettsheffield** [comment]
Thanks for this Gavin.

Libreum is built with Librestack, so it needs to run from within that.  It was built as a demo of Librestack and Librecast's multicast library.  It won't work with node.js, as node.js doesn't have support for the librecast websockets protocol, or librecast.

I agree it needs to be easier to deploy, but so far it is just a quick and dirty demo of the stack - mainly to show how simple a chat server can be, and to demonstrate the power of multicast for organising group communications.

There's a demo instance running at https://chat.librecast.net/

**Comment by ghenry** [comment]
Understood!
